spring:
  datasource:
    username: postgres
    password: ESD2023
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/marjanepromotion
  jpa:
    hibernate:
      ddl-auto: update
  liquibase:
    change-log: db/changelog/db.changelog-master.xml
  mail:
    host: smtp.xxx.com
    username: xxx@xxx.com
    password: xxxxx
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true


