spring:
  datasource:
    username: postgres
    password: 2002pm
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/marjanepromotion
  jpa:
    hibernate:
      ddl-auto: update
  mail:
    host: smtp.google.com
    username: elgountariayoub22@gmail.com
    password: xxxxx
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  liquibase:
    change-log: db/changelog/db.changelog-master.xml


